### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by samkuhn** [AlexEngelhardt/startup-name-generator#1]
I'd really like to give this a spin, but can't seem to get it to work:
```shell
python generate.py -h
  File "generate.py", line 84
    print("epoch " + str(epoch) + ": ", end="")
SyntaxError: invalid syntax
```

(Tried on OSX and Ubuntu)

**Comment by samkuhn** [comment]
Actually it doesn't error when using python3, but there's no output for this command:

```shell
python3 ./generate.py -n 10 -t 4.2 -m models/gallic_500epochs.h5 wordlists/gallic.txt --suffix Software
```

I'm pretty unfamiliar with Python so not sure whats up!

**Comment by AlexEngelhardt** [comment]
Hi,
it's likely you are missing some python package (tensorflow maybe).

I just ran it on a new computer and had the same problem. The code was accidentally hiding too many error messages.

I've just changed it to print them instead. Could you try out the new version? You'll probably get some output now, I bet it'll tell you that some package is missing.

Sorry for the bug, and good luck :)
